# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nidhin Harilal
short_title: Nidhin
email: nidhin.harilal@colorado.edu
description: cryptonymous9
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cryptonymous9.github.io/" # the base hostname & protocol for your site
twitter_username: nidhinhrl
github_username:  cryptonymous9
scholar_username: Twbq4AEAAAAJ&hl=en&oi=ao
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
math_engine: mathjax